version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:maxlan1403@db/CRM_SERG
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=CRM_SERG
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxlan1403
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: