
version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=CRM-bank
      - POSTGRES_USER=gen_user
      - POSTGRES_PASSWORD=maxlan1403
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
