# Generated by Django 5.0.6 on 2024-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
