# Generated by Django 5.0.6 on 2024-06-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email_alter_client_name_and_more'),
        ('reminders', '0003_alter_reminder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Напоминание'),
        ),
    ]
