# Generated by Django 5.0.6 on 2024-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
