# Generated by Django 5.0.6 on 2024-06-08 14:04

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_delete_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/pdf_files'), upload_to='pdf_files', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='client',
            name='xml_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/xml_files'), upload_to='xml_files', verbose_name='XML файл'),
        ),
        migrations.CreateModel(
            name='ClientPDFView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/pdf_files'), upload_to='pdf_files')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientXMLView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/xml_files'), upload_to='xml_files')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_files', to='clients.client')),
            ],
        ),
    ]
