# Generated by Django 5.0.6 on 2024-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='client_files/pdf', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='client',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='client_files/word', verbose_name='Word файл'),
        ),
        migrations.AddField(
            model_name='client',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='client_files/xml', verbose_name='XML файл'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
