# Generated by Django 5.0.6 on 2024-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email_alter_client_name_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='clients',
            field=models.ManyToManyField(related_name='reports', to='clients.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
    ]
